<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $abidjan = City::where('slug', 'abidjan')->first();

        $vehicles = [
            [
                'city_id'               => $abidjan->id,
                'brand'                 => 'TOYOTA',
                'model'                 => 'LAND CRUISER V8',
                'name'                  => 'Toyota Land Cruiser V8',
                'slug'                  => 'toyota-land-cruiser-v8',
                'image'                 => 'vehicles/toyota-land-cruiser-v8.jpg',
                'price_per_day'         => 150000,
                'deposit_amount'        => 500000,
                'km_price'              => 500,
                'weekly_price'          => 800000,
                'monthly_classic_price' => 2500000,
                'monthly_premium_price' => 3500000,
                'year'                  => '2023',
                'gearbox'               => 'Automatique',
                'power'                 => '304 ch',
                'seats'                 => 7,
                'fuel'                  => 'Diesel',
                'carplay'               => true,
                'description'           => 'Le Toyota Land Cruiser V8 2023 est la référence absolue en matière de robustesse, de fiabilité et de confort tout-terrain.',
                'details'               => [
                    'Intérieur' => [
                        '7 places (2+3+2), sellerie cuir premium perforé.',
                        'Écran tactile multimédia 12,3″ avec navigation.',
                        'Climatisation automatique tri-zone.',
                        'Sièges avant ventilés, chauffants, réglage électrique 14 directions.',
                        'Système audio JBL Premium 14 haut-parleurs, Apple CarPlay & Android Auto.',
                        'Coffre : 259 litres (7 places), 1 131 litres (5 places).',
                    ],
                    'Extérieur' => [
                        'Design : Imposant et robuste, lignes horizontales signature Toyota.',
                        'Jantes alliage 20″, pneus tout-terrain.',
                        'Phares Bi-LED adaptatifs avec lave-phares.',
                        'Dimensions : 4 950 × 1 980 × 1 945 mm, empattement 2 850 mm.',
                        'Garde au sol : 230 mm, poids à vide : 2 490 kg.',
                    ],
                    'Moteur & performances' => [
                        'Moteur : V6 3,3 L turbo-diesel twin-turbo (F33A-FTV).',
                        'Puissance : 304 ch (227 kW) à 4 000 tr/min.',
                        'Couple : 700 Nm entre 1 600 et 2 600 tr/min.',
                        'Transmission : Boîte automatique Direct Shift à 10 rapports, 4×4 permanent.',
                        '0–100 km/h : 7,7 s, vitesse maxi : 210 km/h.',
                        'Consommation mixte : 8,9 l/100 km.',
                    ],
                    'Technologies' => [
                        'Toyota Safety Sense : freinage d\'urgence, détection piétons/cyclistes.',
                        'Multi-Terrain Select : 6 modes de conduite tout-terrain.',
                        'Suspension adaptative KDSS (Kinetic Dynamic Suspension System).',
                        'Caméra 360° Multi-Terrain Monitor.',
                        'Régulateur de vitesse adaptatif, aide au maintien de voie.',
                    ],
                ],
                'is_available'          => true,
            ],
            [
                'city_id'               => $abidjan->id,
                'brand'                 => 'MERCEDES-BENZ',
                'model'                 => 'GLE 350',
                'name'                  => 'Mercedes-Benz GLE 350',
                'slug'                  => 'mercedes-gle-350-abidjan',
                'image'                 => 'vehicles/mercedes-gle-350.jpg',
                'price_per_day'         => 120000,
                'deposit_amount'        => 400000,
                'km_price'              => 400,
                'weekly_price'          => 650000,
                'monthly_classic_price' => 2000000,
                'monthly_premium_price' => 3000000,
                'year'                  => '2022',
                'gearbox'               => 'Automatique',
                'power'                 => '258 ch',
                'seats'                 => 5,
                'fuel'                  => 'Diesel',
                'carplay'               => true,
                'description'           => 'Le Mercedes-Benz GLE 350 d 4MATIC est un SUV premium qui conjugue luxe, puissance et polyvalence.',
                'details'               => [
                    'Intérieur' => [
                        '5 places, sellerie cuir nappa avec surpiqûres.',
                        'Système MBUX avec double écran 12,3″, commandes vocales « Hey Mercedes ».',
                        'Climatisation automatique THERMOTRONIC 4 zones.',
                        'Sièges avant à mémoire, chauffants, réglage électrique.',
                        'Système audio Burmester® surround, Apple CarPlay & Android Auto.',
                        'Coffre : 630 litres, extensible à 2 055 litres.',
                    ],
                    'Extérieur' => [
                        'Design : Lignes fluides et musclées, calandre chromée étoilée.',
                        'Jantes alliage AMG 20″ multibranches.',
                        'Phares MULTIBEAM LED adaptatifs.',
                        'Dimensions : 4 924 × 1 947 × 1 772 mm, empattement 2 935 mm.',
                        'Pack AMG Line extérieur, barres de toit aluminium.',
                    ],
                    'Moteur & performances' => [
                        'Moteur : 6 cylindres en ligne, 2 925 cm³, turbo-diesel.',
                        'Puissance : 258 ch (190 kW) à 3 600 tr/min.',
                        'Couple : 600 Nm entre 1 200 et 3 200 tr/min.',
                        'Transmission : Boîte automatique 9G-TRONIC, 4MATIC intégrale.',
                        '0–100 km/h : 6,5 s, vitesse maxi : 230 km/h.',
                        'Consommation mixte : 7,3 l/100 km, CO₂ : 192 g/km.',
                    ],
                    'Technologies' => [
                        'Active Brake Assist : freinage d\'urgence automatique.',
                        'DISTRONIC : régulateur adaptatif avec Stop & Go.',
                        'Active Steering Assist, Active Lane Keeping Assist.',
                        'Caméra 360°, aide au stationnement automatique PARKTRONIC.',
                        'Mercedes me Connect, navigation en réalité augmentée.',
                    ],
                ],
                'is_available'          => true,
            ],
            [
                'city_id'               => $abidjan->id,
                'brand'                 => 'LEXUS',
                'model'                 => 'LX 570',
                'name'                  => 'Lexus LX 570',
                'slug'                  => 'lexus-lx-570',
                'image'                 => 'vehicles/lexus-lx-570.jpg',
                'price_per_day'         => 180000,
                'deposit_amount'        => 600000,
                'km_price'              => 600,
                'weekly_price'          => 900000,
                'monthly_classic_price' => 2800000,
                'monthly_premium_price' => 3800000,
                'year'                  => '2023',
                'gearbox'               => 'Automatique',
                'power'                 => '362 ch',
                'seats'                 => 7,
                'fuel'                  => 'Essence',
                'carplay'               => true,
                'description'           => 'Le Lexus LX 570 est l\'incarnation du luxe suprême associé à une capacité tout-terrain exceptionnelle.',
                'details'               => [
                    'Intérieur' => [
                        '7 places (2+3+2), sellerie cuir semi-aniline.',
                        'Écran multimédia 12,3″ avec Remote Touch, navigation.',
                        'Climatisation automatique 4 zones indépendantes.',
                        'Sièges avant ventilés, chauffants, réglage électrique 20 directions.',
                        'Système audio Mark Levinson® 19 haut-parleurs, Apple CarPlay & Android Auto.',
                        'Coffre : 300 litres (7 places), 1 200 litres (5 places).',
                    ],
                    'Extérieur' => [
                        'Design : Calandre spindle imposante, lignes sculpturales.',
                        'Jantes alliage 21″ multibranches argent.',
                        'Phares à triple faisceau LED adaptatifs, feux arrière à LED.',
                        'Dimensions : 5 080 × 1 980 × 1 910 mm, empattement 2 850 mm.',
                        'Garde au sol : 225 mm, poids à vide : 2 670 kg.',
                    ],
                    'Moteur & performances' => [
                        'Moteur : V8 5,7 L atmosphérique (3UR-FE).',
                        'Puissance : 362 ch (270 kW) à 5 600 tr/min.',
                        'Couple : 530 Nm à 3 200 tr/min.',
                        'Transmission : Boîte automatique à 8 rapports, 4×4 permanent.',
                        '0–100 km/h : 7,7 s, vitesse maxi : 220 km/h.',
                        'Consommation mixte : 14,4 l/100 km.',
                    ],
                    'Technologies' => [
                        'Lexus Safety System+ : freinage pré-collision, détection piétons.',
                        'Crawl Control : gestion automatique tout-terrain basse vitesse.',
                        'Multi-Terrain Select : 5 modes de conduite.',
                        'Suspension adaptative AVS (Adaptive Variable Suspension).',
                        'Caméra 360°, aide au stationnement, régulateur adaptatif.',
                    ],
                ],
                'is_available'          => true,
            ],
            [
                'city_id'               => $abidjan->id,
                'brand'                 => 'BMW',
                'model'                 => 'X5 XDRIVE',
                'name'                  => 'BMW X5 xDrive',
                'slug'                  => 'bmw-x5-xdrive-abidjan',
                'image'                 => 'vehicles/bmw-x5-xdrive.jpg',
                'price_per_day'         => 130000,
                'deposit_amount'        => 450000,
                'km_price'              => 450,
                'weekly_price'          => 700000,
                'monthly_classic_price' => 2200000,
                'monthly_premium_price' => 3200000,
                'year'                  => '2022',
                'gearbox'               => 'Automatique',
                'power'                 => '286 ch',
                'seats'                 => 5,
                'fuel'                  => 'Diesel',
                'carplay'               => true,
                'description'           => 'Le BMW X5 xDrive30d est un SAV qui repousse les limites du luxe et de la polyvalence.',
                'details'               => [
                    'Intérieur' => [
                        '5 places, sellerie cuir Vernasca étendu.',
                        'BMW Live Cockpit Professional : double écran incurvé 12,3″ + 14,9″.',
                        'Climatisation automatique 4 zones.',
                        'Sièges avant ventilés, chauffants, massants, réglage électrique à mémoire.',
                        'Système audio Harman Kardon surround, Apple CarPlay & Android Auto.',
                        'Coffre : 650 litres, extensible à 1 870 litres.',
                    ],
                    'Extérieur' => [
                        'Design : Silhouette imposante et athlétique, calandre BMW illuminée.',
                        'Jantes alliage M 22″ bicolores.',
                        'Phares Laserlight adaptatifs portée 600 m.',
                        'Dimensions : 4 922 × 2 004 × 1 745 mm, empattement 2 975 mm.',
                        'Pack M Sport, accents Shadow Line noir brillant.',
                    ],
                    'Moteur & performances' => [
                        'Moteur : 6 cylindres en ligne, 2 993 cm³, turbo-diesel mild-hybrid 48V.',
                        'Puissance : 286 ch (210 kW) à 4 000 tr/min.',
                        'Couple : 650 Nm entre 1 500 et 2 500 tr/min.',
                        'Transmission : Boîte automatique Steptronic Sport à 8 rapports, xDrive.',
                        '0–100 km/h : 6,1 s, vitesse maxi : 243 km/h.',
                        'Consommation mixte : 6,8 l/100 km, CO₂ : 179 g/km.',
                    ],
                    'Technologies' => [
                        'Driving Assistant Professional : conduite semi-autonome niveau 2.',
                        'Régulateur adaptatif Stop & Go, changement de voie assisté.',
                        'Caméra 360° avec vue drone, stationnement automatique.',
                        'BMW Intelligent Personal Assistant : commandes vocales IA.',
                        'BMW Connected Drive, Digital Key Plus (iPhone/UWB).',
                    ],
                ],
                'is_available'          => true,
            ],
            [
                'city_id'               => $abidjan->id,
                'brand'                 => 'SUZUKI',
                'model'                 => 'FRONX',
                'name'                  => 'Suzuki Fronx',
                'slug'                  => 'suzuki-fronx',
                'image'                 => 'vehicles/suzuki-fronx.jpg',
                'price_per_day'         => 45000,
                'deposit_amount'        => 150000,
                'km_price'              => 200,
                'weekly_price'          => 250000,
                'monthly_classic_price' => 800000,
                'monthly_premium_price' => 1200000,
                'year'                  => '2024',
                'gearbox'               => 'Automatique',
                'power'                 => '100 ch',
                'seats'                 => 5,
                'fuel'                  => 'Essence',
                'carplay'               => true,
                'description'           => 'Le Suzuki Fronx 2024 est un SUV compact au design audacieux, parfait pour la ville comme pour les escapades.',
                'details'               => [
                    'Intérieur' => [
                        '5 places, sellerie tissu/cuir synthétique bicolore.',
                        'Écran tactile multimédia 9″ SmartPlay Pro+.',
                        'Climatisation automatique.',
                        'Sièges avant réglables en hauteur, volant multifonction gainé cuir.',
                        'Système audio 6 haut-parleurs, Apple CarPlay & Android Auto sans fil.',
                        'Coffre : 308 litres.',
                    ],
                    'Extérieur' => [
                        'Design : Lignes coupé dynamiques, silhouette sportive et compacte.',
                        'Jantes alliage 16″ diamantées bicolores.',
                        'Phares LED projecteurs avec feux de jour LED en C.',
                        'Dimensions : 3 995 × 1 765 × 1 550 mm, empattement 2 520 mm.',
                        'Toit flottant noir, barres de toit intégrées.',
                    ],
                    'Moteur & performances' => [
                        'Moteur : 3 cylindres Boosterjet turbo, 998 cm³.',
                        'Puissance : 100 ch (74 kW) à 5 500 tr/min.',
                        'Couple : 148 Nm entre 1 700 et 4 000 tr/min.',
                        'Transmission : Boîte automatique à 6 rapports.',
                        '0–100 km/h : 10,0 s, vitesse maxi : 190 km/h.',
                        'Consommation mixte : 5,0 l/100 km, CO₂ : 114 g/km.',
                    ],
                    'Technologies' => [
                        'Suzuki Safety Support : freinage d\'urgence automatique, détection piétons.',
                        'Alerte de franchissement de voie, reconnaissance des panneaux.',
                        'Caméra de recul avec lignes de guidage dynamiques.',
                        'Régulateur de vitesse adaptatif.',
                        'Affichage tête haute (HUD) couleur.',
                    ],
                ],
                'is_available'          => true,
            ],
        ];

        foreach ($vehicles as $v) {
            Vehicle::updateOrCreate(['slug' => $v['slug']], $v);
        }
    }
}
